# steps:
# # Build the container image
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 'gcr.io/PROJECT_ID/IMAGE', '.']
# # Push the container image to Container Registry
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'gcr.io/PROJECT_ID/IMAGE']
# # Deploy container image to Cloud Run
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   entrypoint: gcloud
#   args: ['run', 'deploy', 'SERVICE-NAME', '--image', 'gcr.io/PROJECT_ID/IMAGE', '--region', 'REGION', '--platform', 'managed', '--port', '3000']
# images:
# - gcr.io/PROJECT_ID/IMAGE




steps:
# Install nide packages
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

# Build productive files
- name: 'gcr.io/cloud-builders/npm'
  args: ['run' , 'build' , '--prod']

# Deploy to google cloud
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app' , 'deploy' , '--version=prod']
